package com.hippo.ehviewer.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "REMOTE_PUSH".
*/
public class RemotePushInfoDao extends AbstractDao<RemotePushInfo, Long> {

    public static final String TABLENAME = "REMOTE_PUSH";

    /**
     * Properties of entity RemotePushInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Gid = new Property(0, long.class, "gid", true, "GID");
        public final static Property Token = new Property(1, String.class, "token", false, "TOKEN");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property TitleJpn = new Property(3, String.class, "titleJpn", false, "TITLE_JPN");
        public final static Property Thumb = new Property(4, String.class, "thumb", false, "THUMB");
        public final static Property Category = new Property(5, Integer.class, "category", false, "CATEGORY");
        public final static Property Posted = new Property(6, String.class, "posted", false, "POSTED");
        public final static Property Uploader = new Property(7, String.class, "uploader", false, "UPLOADER");
        public final static Property Rating = new Property(8, Float.class, "rating", false, "RATING");
        public final static Property PushTime = new Property(9, long.class, "pushTime", false, "PUSH_TIME");
    };


    public RemotePushInfoDao(DaoConfig config) {
        super(config);
    }
    
    public RemotePushInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"REMOTE_PUSH\" (" + //
                "\"GID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: gid
                "\"TOKEN\" TEXT," + // 1: token
                "\"TITLE\" TEXT," + // 2: title
                "\"TITLE_JPN\" TEXT," + // 3: titleJpn
                "\"THUMB\" TEXT," + // 4: thumb
                "\"CATEGORY\" INTEGER," + // 5: category
                "\"POSTED\" TEXT," + // 6: posted
                "\"UPLOADER\" TEXT," + // 7: uploader
                "\"RATING\" REAL," + // 8: rating
                "\"PUSH_TIME\" INTEGER NOT NULL );"); // 9: pushTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REMOTE_PUSH\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RemotePushInfo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getGid());
 
        String token = entity.getToken();
        if (token != null) {
            stmt.bindString(2, token);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String titleJpn = entity.getTitleJpn();
        if (titleJpn != null) {
            stmt.bindString(4, titleJpn);
        }
 
        String thumb = entity.getThumb();
        if (thumb != null) {
            stmt.bindString(5, thumb);
        }
 
        Integer category = entity.getCategory();
        if (category != null) {
            stmt.bindLong(6, category);
        }
 
        String posted = entity.getPosted();
        if (posted != null) {
            stmt.bindString(7, posted);
        }
 
        String uploader = entity.getUploader();
        if (uploader != null) {
            stmt.bindString(8, uploader);
        }
 
        Float rating = entity.getRating();
        if (rating != null) {
            stmt.bindDouble(9, rating);
        }
        stmt.bindLong(10, entity.getPushTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RemotePushInfo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getGid());
 
        String token = entity.getToken();
        if (token != null) {
            stmt.bindString(2, token);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String titleJpn = entity.getTitleJpn();
        if (titleJpn != null) {
            stmt.bindString(4, titleJpn);
        }
 
        String thumb = entity.getThumb();
        if (thumb != null) {
            stmt.bindString(5, thumb);
        }
 
        Integer category = entity.getCategory();
        if (category != null) {
            stmt.bindLong(6, category);
        }
 
        String posted = entity.getPosted();
        if (posted != null) {
            stmt.bindString(7, posted);
        }
 
        String uploader = entity.getUploader();
        if (uploader != null) {
            stmt.bindString(8, uploader);
        }
 
        Float rating = entity.getRating();
        if (rating != null) {
            stmt.bindDouble(9, rating);
        }
        stmt.bindLong(10, entity.getPushTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public RemotePushInfo readEntity(Cursor cursor, int offset) {
        RemotePushInfo entity = new RemotePushInfo( //
            cursor.getLong(offset + 0), // gid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // token
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // titleJpn
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // thumb
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // category
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // posted
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // uploader
            cursor.isNull(offset + 8) ? null : cursor.getFloat(offset + 8), // rating
            cursor.getLong(offset + 9) // pushTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RemotePushInfo entity, int offset) {
        entity.setGid(cursor.getLong(offset + 0));
        entity.setToken(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTitleJpn(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setThumb(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCategory(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setPosted(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setUploader(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setRating(cursor.isNull(offset + 8) ? null : cursor.getFloat(offset + 8));
        entity.setPushTime(cursor.getLong(offset + 9));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RemotePushInfo entity, long rowId) {
        entity.setGid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RemotePushInfo entity) {
        if(entity != null) {
            return entity.getGid();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
