package com.hippo.ehviewer.dao;

import org.greenrobot.greendao.annotation.*;
import com.alibaba.fastjson.JSONObject;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "REMOTE_PUSH".
 */
@Entity(nameInDb = "REMOTE_PUSH")
public class RemotePushInfo {

	@Id
	public long gid;
	public String token;
	public String title;
	public String titleJpn;
	public String thumb;
	public Integer category;
	public String posted;
	public String uploader;
	public Float rating;
	public long pushTime;

	@Generated
	public RemotePushInfo() {
	}

	public RemotePushInfo(long gid) {
		this.gid = gid;
	}

	@Generated
	public RemotePushInfo(long gid, String token, String title, String titleJpn, String thumb, Integer category,
			String posted, String uploader, Float rating, long pushTime) {
		this.gid = gid;
		this.token = token;
		this.title = title;
		this.titleJpn = titleJpn;
		this.thumb = thumb;
		this.category = category;
		this.posted = posted;
		this.uploader = uploader;
		this.rating = rating;
		this.pushTime = pushTime;
	}

	public long getGid() {
		return gid;
	}

	public void setGid(long gid) {
		this.gid = gid;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitleJpn() {
		return titleJpn;
	}

	public void setTitleJpn(String titleJpn) {
		this.titleJpn = titleJpn;
	}

	public String getThumb() {
		return thumb;
	}

	public void setThumb(String thumb) {
		this.thumb = thumb;
	}

	public Integer getCategory() {
		return category;
	}

	public void setCategory(Integer category) {
		this.category = category;
	}

	public String getPosted() {
		return posted;
	}

	public void setPosted(String posted) {
		this.posted = posted;
	}

	public String getUploader() {
		return uploader;
	}

	public void setUploader(String uploader) {
		this.uploader = uploader;
	}

	public Float getRating() {
		return rating;
	}

	public void setRating(Float rating) {
		this.rating = rating;
	}

	public long getPushTime() {
		return pushTime;
	}

	public void setPushTime(long pushTime) {
		this.pushTime = pushTime;
	}

	@Override
	public String toString() {
		return title;
	}

	public JSONObject toJson() {
		JSONObject object = new JSONObject();
		object.put("gid", gid);
		object.put("token", token);
		object.put("title", title);
		object.put("titleJpn", titleJpn);
		object.put("thumb", thumb);
		object.put("category", category);
		object.put("posted", posted);
		object.put("uploader", uploader);
		object.put("rating", rating);
		object.put("pushTime", pushTime);
		return object;
	}

}
